### ISSUE TITLE
Change Development Database

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#10]
To mimic the database structure on Production. Change the app to want to connect to a database named blackbook_dev using a "developer" user. Then write instructions for how a new developer is supposed to set this up and add it to our readme.

After it is set up. Modify express.js to connect to this prod database when the environment variable is set to `development`.

**Comment by aaronpflaumer** [comment]
62b1e9eb63d8fc22d7e92ebcc8b6adbc36b2d5f6
