### ISSUE TITLE
Write "Seed" and "Reset" SQL scripts.

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#11]
A file that has many commands that are supposed to be executed sequentially with a single command is called a "Script". You will need to make two SQL scripts that will set up the tables in our database with either dummy data or empty tables.

Both of these scripts will drop and recreate all tables in the database. The seed script will go one step further and add lots of false data, generated so that the app can be usable on development. 

Drop these scripts in a new `database` folder at the root level of the project.

Seed data needs... 
Fake users for login - Some admin, some not.
Fake Books - Some shared, some not.
Fake Characters - Some related, some not.
Fake Tags on all characters and relationships.

**Comment by devinleonhart** [comment]
@aaronpflaumer If you're finished with this issue, please close it.

**Comment by aaronpflaumer** [comment]
e2363537cf617f1fec460e52a67e6f8354d44b01
