### ISSUE TITLE
Extend Express.js API to include all "Rails" routes.

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#12]
Right now, we have a very basic API (Application Programming Interface). When our front-end _application_, _interfaces_ with our server, it's going to be making one of 4 types of http requests.

`GET` Requests are associated with receiving data.
`POST` Requests are for creating data.
`PUT` Requests are for updating existing data.
`DELETE` requests are obvious. 

Our API needs to know what happens when a particular request hits a particular URL. Like, what does the server do when someone makes a GET request at `/api/books`? Does it return everything we know about a book? All books?

Ruby on Rails created a convention used by a lot of developers today to explain what should happen.

`GET` on a `/` path means it's an `INDEX` route. This basically means ```Get everything associated with the path.``` Like GET on `/api/books/` means ```Get me all data about all books```

GET on `books/:id` means ```Get me all all data about one book. Specifically the one that has the id I just gave you in the URL.``` We call this a `SHOW` route.

POST on `books/:name/:description/:etc` means ```I'm going to make a new book and pass you all information you need to make a new book.``` We call this a `CREATE` route. 

PUT on `books/:id/:name/:description/:etc` means ```I'm going to update an existing book with new data. Here's the ID for the one I want, and the data I'm going to give it.``` We call this an `UPDATE` route.

DELETE on `books/:id` is the most intuitive. It means ```Delete the book with the given id.``` We call this a DESTROY route.

Your task is to extend the API to encompass all routes that make sense and then map those routes to queries that do not return more information than is required. 

As an example,
```
// Book.index -> Returns list of all books.
exports.index = function(req, res) {

  connect.query("SELECT id, name FROM book", req, res);

};
```

This code in our API returns the id and name of all books. It's the index route for book. And we refer to that in shorthand as `Book.index` It is up to you to determine if something should get a route. Like, is there a time when we need to list all Books? Definitely. So it gets a `Book.index` route. Does it make sense to List all characters for a book? Yes. But it doesn't make sense to list all characters for ALL books. So that means that Character.index needs to exist, yet will certainly take a `book_id` parameter.

**Comment by aaronpflaumer** [comment]
aa8f3b6692e141dae457c887ff4fa602b3f0950d
