### ISSUE TITLE
Finish all "book" workflows.

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#16]
Now that we're to UI design. We need to consider those [workflows](https://github.com/devinleonhart/blackbook/wiki/Intended-Workflows) we made back at the start. You need to work out with a client what they were really looking for when they commissioned you. What does the user of the system actually do when they use your app?

The "book" workflows" are the first thing we need to manage. As is it's the first level of object the user deals with after logging in. We need to allow the user to...

Add a new book.
View an existing book.
Edit an existing book.
Delete a book.

Does that look familiar? It should by now. HTTP requests have POST, GET, PUT, and DELETE for those same things. And Rails conventions gives us CREATE, INDEX or SHOW, EDIT, and DELETE for the exact same things.

This is commonly known as "CRUD" as most things in webapps have to have a create/read/update/delete pattern. Create UI elements that will let users perform these actions. And it's best to focus on them one at a time.

**Comment by aaronpflaumer** [comment]
23e8b1d12066edaba99241a01308fe67beeabcc2
