### ISSUE TITLE
Build Requirements Documentation

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#2]
Before any code is written, you should understand the end goal for the project you are working on. "Requirements Documentation" is a formalization of what the client wants and agrees to pay for. Build requirements documentation for blackbook and save this documentation into the Blackbook Wiki. Keep all documentation out of the blackbook repository. 

There are many examples available online for requirements documentation. However many of them are excessively formal to stand up to legal scrutiny. The requirements document should be of your own design to help you with understanding the project as a whole and what the client (me, in this case) is asking for.

**Comment by aaronpflaumer** [comment]
@devinleonhart Please review.
