### ISSUE TITLE
Plan Models and ERD

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#3]
Models, in software development, are the conceptual "things" your application keeps track of. If your application keeps track of users logging in and out, you need a User model. If your application tracks baseball statistics from games, perhaps it needs a "Player" and "Game" model. If you have to keep track of it. You need a model for it.

An [entity relationship diagram] (https://en.wikipedia.org/wiki/Entity%E2%80%93relationship_model) is a visual representation of how the models are related to one another and what the system tracks. 

Plan out the models and ERD based on the requirements documentation. Save the ERD to `project-documentation/models`. Save all text-based model information to the blackbook wiki.

**Comment by aaronpflaumer** [comment]
265ac3da6e4902e9b89265c91526806cf8d7281a
