### ISSUE TITLE
Plan UI and Intended Workflows

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#4]
Create extremely basic wire frames for how you believe the user experience should look. Every new experience the user encounters, like a new page, or a new popup, should be documented. Save these wireframes into a root folder called `project-documentation/wireframes` in the repo.

"Intended Workflows" on the other hand are a description of all the actions a user takes through the UI. For example... "User visits index page. Use is provided with login prompt. Under enters credentials. User clicks login button..." etc. This makes sure you understand all that needs to be created before you begin actual development and nothing catches you by surprise. Save this into the blackbook wiki.

**Comment by aaronpflaumer** [comment]
0333efab96006ecf17c88c548484cd965bcafd86
