### ISSUE TITLE
Implement Deployment Strategy

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#6]
Once we have figured out what technologies we want to use, we will then figure out how it will be hosted and thus usable. [Heroku](https://www.heroku.com/) is a viable option. But ideally, I would prefer we work on a deployment strategy for deploying to our own server on [Digital Ocean](https://www.digitalocean.com/) so that we have better control. 

A deployment tool will have to be researched for the project and it should make use of SSH keys for security.

**Comment by aaronpflaumer** [comment]
a945f5192bdfe8fd76af5611a5b47e22c20fb720
