### ISSUE TITLE
Create Readme

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#8]
Once everything is in place, you need to create documentation that will let other developers join you on the project. After doing all of the previous steps, only you now know how to set everything up from scratch. You need to create a readme file that allows devs to follow a series of steps to begin work. 

For example, if certain commands must be run to set up a database on a developer's machine, then those commands must be in the readme so that the developer can join you. 

It is suggested that after you make the readme, you should be able to clear your setup, follow the readme, and get back to where you were before.

**Comment by aaronpflaumer** [comment]
4a660c6017d50da2ae6f0080b5b649d7ded994c6
