### ISSUE TITLE
Create Production Database

### ISSUE THREAD

**Issue by devinleonhart** [devinleonhart/blackbook#9]
Use `apt-get` on our server to install postgres. Then create the production database named `blackbook_prod`. Make sure that the `developer` user on production has full access to this database. 

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-postgresql-on-ubuntu-12-04 Should be very helpful.

After it is set up. Modify express.js to connect to this prod database when the environment variable is set to `production`.

**Comment by aaronpflaumer** [comment]
03624e75ea13281439d85cd361bb4fe0fd2fb8cf
